apiVersion: v1
kind: Service
metadata:
  name: {{ include "bigbox-hoppscotch.fullname" . }}-svc
  labels:
    {{- include "bigbox-hoppscotch.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "bigbox-hoppscotch.selectorLabels" . | nindent 4 }}
  ports:
    - name: client
      targetPort: client
      port: 3000
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.client.port }}
      {{- end }}
    - name: admin
      targetPort: admin
      port: 3100
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.admin.port }}
      {{- end }}
    - name: backend
      targetPort: backend
      port: 3170
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.backend.port }}
      {{- end }}