apiVersion: v1
kind: Service
metadata:
  name: {{ include "bigbox-nats.fullname" . }}-svc
  labels:
    {{- include "bigbox-nats.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "bigbox-nats.selectorLabels" . | nindent 4 }}
  ports:
    - name: client
      targetPort: client
      port: 4222
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.client }}
      {{- end }}
    - name: monitoring
      targetPort: monitoring
      port: 8222
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.monitoring }}
      {{- end }}
