apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bigbox-sftp.fullname" . }}-secret
  labels:
    {{- include "bigbox-sftp.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
type: Opaque
data:
  clientPublicKey: {{ required "ğŸš¨ La clÃ© SSH publique du client encodÃ©e en base64 est obligatoire : --set sftp.clientPublicKey=# ğŸš¨" .Values.sftp.clientPublicKey | quote }}
