apiVersion: v1
kind: Service
metadata:
  name: {{ include "bigbox-postgresql.fullname" . }}-svc
  labels:
    {{- include "bigbox-postgresql.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "bigbox-postgresql.selectorLabels" . | nindent 4 }}
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.port }}
      {{- end }}
