apiVersion: v1
kind: Service
metadata:
  name: {{ include "bigbox-nui.fullname" . }}-svc
  labels:
    {{- include "bigbox-nui.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "bigbox-nui.selectorLabels" . | nindent 4 }}
  ports:
    - name: client
      targetPort: client
      port: 31311
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.port }}
      {{- end }}
