apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bigbox-wiremock.fullname" . }}
  labels:
    {{- include "bigbox-wiremock.labels" . | nindent 4 }}
    app.kubernetes.io/component: "test-tools"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bigbox-wiremock.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bigbox-wiremock.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: wiremock
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: "/__admin/health"
              port: http
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: "/__admin/health"
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: wiremock-files
              mountPath: /home/wiremock/__files
            - name: wiremock-mappings
              mountPath: /home/wiremock/mappings
      volumes:
        - name: wiremock-files
          persistentVolumeClaim:
            claimName: {{ include "bigbox-wiremock.fullname" . }}-files-pvc
        - name: wiremock-mappings
          persistentVolumeClaim:
            claimName: {{ include "bigbox-wiremock.fullname" . }}-mappings-pvc
