apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bigbox-wiremock.fullname" . }}-files-pvc
  labels:
    {{- include "bigbox-wiremock.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClassName }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bigbox-wiremock.fullname" . }}-mappings-pvc
  labels:
    {{- include "bigbox-wiremock.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClassName }}