apiVersion: v1
kind: Service
metadata:
  name: {{ include "bigbox-wiremock.fullname" . }}-svc
  labels:
    {{- include "bigbox-wiremock.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "bigbox-wiremock.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      targetPort: http
      port: 8080
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.port }}
      {{- end }}