apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bigbox-nui.fullname" . }}-cfg
  labels:
    {{- include "bigbox-nui.labels" . | nindent 4 }}
data:
  bigbox.json: |-
    {
        "description": "NATS BigBox",
        "url": "nats://bigbox-nats-svc:4222",
        "socks_proxy": "",
        "token": "",
        "user": "",
        "password": "",
        "creds": "",
        "nkey": "",
        "cert": "",
        "key": "",
        "ca": "",
        "nsc": "",
        "jetstream_domain": "",
        "jetstream_api_prefix": "",
        "jetstream_event_prefix": "",
        "inbox_prefix": "",
        "user_jwt": "",
        "color_scheme": "",
        "tls_first": false,
        "windows_cert_store": "",
        "windows_cert_match_by": "",
        "windows_cert_match": "",
        "windows_ca_certs_match": null
    }
