apiVersion: v1
kind: Service
metadata:
  name: {{ include "bigbox-sftp.fullname" . }}-svc
  labels:
    {{- include "bigbox-sftp.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "bigbox-sftp.selectorLabels" . | nindent 4 }}
  ports:
    - name: client
      protocol: TCP
      targetPort: 22
      port: 2222
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.client }}
      {{- end }}
